### ISSUE TITLE
Teaching kit wizard

### ISSUE THREAD

**Issue by davidascher** [mozilla/bloodflow#2]

**Comment by davidascher** [comment]
I'd like to understand:
- scope of work in first heartbeat
- stakeholders we need to please by the end (esp: Accountable)
- who'se spending >25% of their time on this (Responsible)
- URL where the work is happening (github repo?)

**Comment by davidascher** [comment]
Simon, I'll explain this repo when we talk.

**Comment by simonwex** [comment]
@davidascher sounds good. When are we talking?
